### ISSUE TITLE
CSRF security & InputFile errors management

### ISSUE THREAD

**Issue by cyrilmhansen** [Putnami/putnami-pwt#109]
I have multiple InputFile in my project and they were working fine in Jetty. But they fail in my production setup, where I use Apache as reverse proxy in front of Tomcat 8. The status requests always return null responses.

I started to read source and finally made my own versions of the server side controller classes to ease spring configuration. Now it seems that I don't understand how the map of ProgressListener is supposed to work in FileTransfertMultipartResolver class.

It seems to me that the issue is that there is an assumption that the different requests coming from each client will be handled by the same thread, and that assumption seems broken in my tomcat setup.

Please can someone clarify the requirement for the FileTransfertMultipartResolver class ? Is some kind of keep Alive required ? In method FileUpload newFileUpload(FileItemFactory fileItemFactory) is there a way to get some reference to the current session ?

**Comment by cyrilmhansen** [comment]
Ok I got it working by disabling security headers in spring security. It seems the framework adds by defaut  'X-Frame-Options' to 'DENY' to headers. In my tomcat 8 setup as a results browsers ignore the responses from / file/upload and /file/status requests. The response of the file/upload request is required to mark the upload as completed.

So my hint is  : use httpSecurity.headers().disable();
or httpSecurity.headers()
       .addHeaderWriter(new XFrameOptionsHeaderWriter(XFrameOptionsMode.SAMEORIGIN));

**Comment by cyrilmhansen** [comment]
My page has no special structure. My site uses the PageDecorator from the tutotial. GWT version is 2.7.0.

**Comment by fdumay** [comment]
Hi,

after a couple of investigation hours, I better understand the topic.

I see 2 points:

**1st :** There is one bug on the InputFile. if the upload request fails, the error is not properly handled and propagated and the upload status request loops without any brake. we're gonna fix it today.

**2nd :** Spring sécurity self protects the ajax requests with the CSRF protocole. Then as PWT doesn't implement it by now, we need to build this feature. Infact it's a quite important security feature so we're gonna to implement it quickly.

The question that still without any answer is : why spring security doesn't secure properly the ajax request on the Jetty lunched from the DevMode? But anyway it doesn't really matter,  where gonna fix it.

So pending, you can disable the CSRF in the spring security configuration with :
```
	http.csrf().disable();
 ```

Thank you, and see you soon.

**Comment by fdumay** [comment]
The CSRF is now available on the client side.
To enable it we just have to add to meta tags in the html such as :
 
```xml
<meta name="_csrf" content="1a5c03bf-62c6-49ba-b497-e5897293bf5a">
<meta name="_csrf_header" content="X-CSRF-TOKEN">
```

Of course  the token must be generated from the server, so we need to turn the html file wich hosts the gwt entry point to a jsp, then add the tag in the head of the page:

```xml
<meta name="_csrf" 
content="<%= ((org.springframework.security.web.csrf.CsrfToken)request
.getAttribute("_csrf")).getToken() %>"/>
```
